# Generated by Django 4.0.2 on 2022-03-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workflowstate",
            constraint=models.UniqueConstraint(
                fields=("page", "workflow"), name="unique_page_in_workflow"
            ),
        ),
    ]
